#!/usr/bin/env python3
"""
Interactive setup script for Gemini Twitch Chat Bot
Creates .env file with user's configuration
"""

import os
import sys

def print_header():
    print("\n" + "="*50)
    print("   🤖 Gemini Twitch Chat Bot Setup")
    print("="*50 + "\n")

def print_step(num, text):
    print(f"\n📌 Step {num}: {text}")
    print("-" * 40)

def get_input(prompt, required=True, default=None):
    """Get user input with optional default value."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    while True:
        value = input(prompt).strip()
        if not value and default:
            return default
        if not value and required:
            print("  ❌ This field is required. Please enter a value.")
            continue
        return value

def get_hidden_input(prompt):
    """Get password-style input (hidden)."""
    import getpass
    while True:
        value = getpass.getpass(f"{prompt}: ").strip()
        if not value:
            print("  ❌ This field is required. Please enter a value.")
            continue
        return value

def main():
    print_header()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  A .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled. Your existing .env file was not modified.")
            sys.exit(0)
    
    print("This wizard will help you set up the bot.\n")
    
    # Step 1: Twitch Token
    print_step(1, "Twitch OAuth Token")
    print("Get your token from: https://twitchtokengenerator.com/")
    print("  1. Click 'Bot Chat Token'")
    print("  2. Authorize with Twitch")
    print("  3. Copy the token (starts with 'oauth:')")
    print()
    twitch_token = get_hidden_input("Paste your Twitch OAuth token")
    if not twitch_token.startswith('oauth:'):
        twitch_token = 'oauth:' + twitch_token
    print("  ✅ Token saved!")
    
    # Step 2: Channel Name
    print_step(2, "Twitch Channel")
    print("Enter the channel name where the bot should respond.")
    print("(This is your Twitch username, without the # symbol)")
    print()
    twitch_channel = get_input("Your Twitch channel name")
    twitch_channel = twitch_channel.lstrip('#').lower()
    print(f"  ✅ Bot will join: #{twitch_channel}")
    
    # Step 3: Gemini API Key
    print_step(3, "Gemini API Key")
    print("Get your API key from: https://aistudio.google.com/app/apikey")
    print("  1. Click 'Create API Key'")
    print("  2. Copy the key")
    print()
    gemini_key = get_hidden_input("Paste your Gemini API key")
    print("  ✅ API key saved!")
    
    # Step 4: Optional Settings
    print_step(4, "Optional Settings")
    print("Press Enter to use defaults.\n")
    
    bot_prefix = get_input("Command prefix", default="!")
    cooldown = get_input("Cooldown between commands (seconds)", default="5")
    
    # Validate cooldown is a number
    try:
        cooldown = str(int(cooldown))
    except ValueError:
        cooldown = "5"
    
    # Write .env file
    env_content = f"""# Gemini Twitch Chat Bot Configuration
# Generated by setup.py

# Twitch OAuth Token
TWITCH_TOKEN={twitch_token}

# Twitch channel to join
TWITCH_CHANNEL={twitch_channel}

# Gemini API Key
GEMINI_API_KEY={gemini_key}

# Command prefix (default: !)
BOT_PREFIX={bot_prefix}

# Cooldown between commands in seconds
COOLDOWN_SECONDS={cooldown}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    # Success!
    print("\n" + "="*50)
    print("   ✅ Setup Complete!")
    print("="*50)
    print(f"""
Your bot is configured for channel: #{twitch_channel}

To start the bot, run:
  python bot.py

Available commands in chat:
  {bot_prefix}ask [question]  - Ask the AI anything
  {bot_prefix}joke            - Get a random joke
  {bot_prefix}fact            - Get an interesting fact  
  {bot_prefix}roast [@user]   - Get a playful roast
  {bot_prefix}help            - Show commands

Happy streaming! 🎮
""")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
